In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np
list1 = [1,2,3,4,5]
x = np.array(list1)

In [3]:
type(x)

numpy.ndarray

**ndarray = one dimentional array****

In [4]:
np.array([2,2,2,2,2])

array([2, 2, 2, 2, 2])

In [5]:
np.array((3,3,3,3)).shape

(4,)

In [6]:

np.array({1,1,1,4})

array({1, 4}, dtype=object)

In [7]:
array2d = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [8]:
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

**2dimentional_array**

In [9]:
array2d.shape

(3, 4)

In [10]:
list_1 = [1,2,3,4,5]
list_2 = [1,2,3,4,5]
array2d_2 = np.array([list_1,list_2])

In [11]:
array2d_2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])